Lab-2/Models/Birth.cs
namespace Labolatorium2.Models
{
    public class Birth
    {
        public DateTime Age { get; set; }
        public string? First_name { get; set; }

        public bool IsValid()
        {
            return Age != null && First_name != null;
        }
        public int Years_Old()
        {
            return DateTime.Now.Year - Age.Year;
        }
    }
}

Lab-2/Models/Calculator.cs
namespace Labolatorium2.Models
{
    public class Calculator
    {
        public double? A { get; set; }
        public double? B { get; set; }
        public Operators? Op { get; set; }

        public bool IsValid()
        {
            return A != null && B != null && Op !=null;
        }
        public double Calculate()
        {
            switch (Op) 
            {
                case Operators.Add:
                    return (double)(A + B);
                case Operators.Sub:
                    return (double)(A - B);
                case Operators.Mul:
                    return (double)(A * B);
                case Operators.Div:
                    return (double)(A / B);
                default: return double.NaN;
            }
        }
    }
}

Lab-2/Models/ErrorViewModel.cs
namespace Labolatorium2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab-2/Models/Operators.cs
namespace Labolatorium2.Models
{
    public enum Operators
    {
        Add, Sub, Mul , Div
    }
}

Lab-2/Controllers/BirthController.cs
using Labolatorium2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Labolatorium2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View();
        }
        public IActionResult Result(Birth model)
        {
            if (!model.IsValid())
            {
                return BadRequest();
            }
            return View(model);
        }
    }
}

Lab-2/Controllers/CalculatorController.cs
using Labolatorium2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Numerics;

namespace Labolatorium2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View();
        }
        public IActionResult Result(Calculator model)
        {
          if (!model.IsValid())
            {
                return BadRequest();
            }
          return View(model);
        }
    }
}

Lab-2/Controllers/HomeController.cs
using Labolatorium2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Labolatorium2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab-2/Views/Birth/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form action="Result" method="get">
    <input type="date" name="age" />
    <input type="text" name="first_name" />
    <button type="submit">Send</button>
</form>

Lab-2/Views/Birth/Result.cshtml
@model Birth
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<H3>Hello @Model.First_name you are @Model.Years_Old() old!</H3>

Lab-2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form action="Result" method="get">
    <input type="number" name="a" step="0.0001"/>
    <input type="text" name="op" />
    <input type="number" name="b" step="0.0001" />
    <button type="submit">Oblicz</button>
</form>

Lab-2/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<H3>@Model.A @Model.Op @Model.B = @Model.Calculate()</H3>

Lab-2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Kalkulator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Birth</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lab1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>